name: practice
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  cupertino_icons: ^1.0.6
  firebase_auth: ^6.1.1
  firebase_database: ^12.0.3
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  location: ^8.0.0
  firebase_storage: ^13.0.3
  intl: ^0.19.0
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.6.1
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0
  file_picker: ^8.1.2
  syncfusion_flutter_pdf: ^25.1.35
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


